create table hotel(
    id number generated by default as identity,
    nome varchar(100),
    primary key(id)
);

create table quarto(
    id number generated by default as identity,
    capacidade number not null,
    quantidade_cama number not null,
    numero varchar(10) not null,
    id_hotel number,
    primary key(id),
    foreign key(id_hotel) references hotel(id)
);

create table pessoa(
    id number generated by default as identity,
    nome varchar(150) not null,
    telefone varchar(20) not null,
    email varchar(50),
    primary key(id),
    unique(telefone)
);

create table reserva(
    id number generated by default as identity,
    checkin date not null,
    checkout date not null,
    status varchar(50) not null,
    id_quarto number,
    id_pessoa number,
    primary key(id),
    foreign key(id_quarto) references quarto(id),
    foreign key(id_pessoa) references pessoa(id)
);

insert into hotel(nome) values('Durma Bem');

insert into quarto(numero, capacidade, quantidade_cama, id_hotel) values('S01', 1, 1, 1);
insert into quarto(numero, capacidade, quantidade_cama, id_hotel) values('S02', 1, 1, 1);
insert into quarto(numero, capacidade, quantidade_cama, id_hotel) values('S03', 1, 1, 1);
insert into quarto(numero, capacidade, quantidade_cama, id_hotel) values('D01', 2, 1, 1);
insert into quarto(numero, capacidade, quantidade_cama, id_hotel) values('D02', 2, 1, 1);
insert into quarto(numero, capacidade, quantidade_cama, id_hotel) values('D03', 2, 2, 1);
insert into quarto(numero, capacidade, quantidade_cama, id_hotel) values('T01', 3, 2, 1);
insert into quarto(numero, capacidade, quantidade_cama, id_hotel) values('T02', 3, 2, 1);
insert into quarto(numero, capacidade, quantidade_cama, id_hotel) values('T03', 3, 3, 1);
