create table k_enquete(
    id number generated by default as identity,
    nome varchar(100),
    criador varchar(100),
    data date,
    primary key(id));

create table k_usuario(
    id number generated by default as identity,
    nome varchar(100),
    telefone varchar(50),
    situacao number default value 1,
    primary key(id));

create table k_pergunta(
    id number generated by default as identity,
    enunciado varchar(150) not null,
    numero number not null,
    tipo varchar(30) not null,
    enquete_id number,
    primary key(id),
    foreign key(enquete_id) references k_enquete(id));

create table k_item(
    id number generated by default as identity,
    descricao varchar(50) not null,
    pergunta_id number,
    primary key(id),
    foreign key(pergunta_id) references k_pergunta(id));

create table k_resposta(
    id number generated by default as identity,
    datahora timestamp,
    valorresposta varchar(100),
    usuario_id number,
    pergunta_id number,
    primary key(id),
    foreign key(usuario_id) references k_usuario(id),
    foreign key(pergunta_id) references k_pergunta(id));

alter table k_enquete add constraint nome_unico unique(nome);