create table time(
    id number generated by default as identity,
    nome varchar(100) not null,
    vitorias number default 0,
    derrotas number default 0,
    empates number default 0,
    gols_pro number default 0,
    gols_contra number default 0,
    primary key(id)
);

create table partida(
    id number generated by default as identity,
    data_hora timestamp not null,
    gols_casa number not null,
    gols_visitante number not null,
    time_casa number,
    time_visitante number,
    local varchar(50),
    foreign key(time_casa) references time(id),
    foreign key(time_visitante) references time(id),
    primary key(id)
);