create table pessoa(
    id number generated by default as identity,
    nome varchar(100),
    email varchar(80),
    cpf varchar(20),
    telefone varchar(20),
    nascimento date,
    primary key(id)
);

create table endereco(
    pessoa_id number,
    logradouro varchar(100),
    cep varchar(15),
    numero varchar(15),
    municipio varchar(50),
    foreign key (pessoa_id) references pessoa(id)
);

create table funcionario(
    id number generated by default as identity,
    cargo varchar(20),
    departamento varchar(20),
    salario number,
    turno varchar(20),
    admissao date,
    pessoa_id number,
    primary key(id),
    foreign key (pessoa_id) references pessoa(id)
);