create table pessoa(
    id number generated by default as identity,
    nome varchar(100),
    email varchar(80),
    cpf varchar(20),
    telefone varchar(20),
    nascimento date,
    primary key(id)
);

create table endereco(
    pessoa_id number,
    logradouro varchar(100),
    cep varchar(15),
    numero varchar(15),
    municipio varchar(50),
    foreign key (pessoa_id) references pessoa(id)
);

create table funcionario(
    id number generated by default as identity,
    cargo varchar(20),
    departamento varchar(20),
    salario number,
    turno varchar(20),
    admissao date,
    pessoa_id number,
    primary key(id),
    foreign key (pessoa_id) references pessoa(id)
);


INSERT INTO PESSOA(NOME, EMAIL, CPF, TELEFONE) VALUES('Geraldo Thomas', 'thomas@fiap.com.br',
                        '32423', '(11) 8343432');

INSERT INTO PESSOA(NOME, EMAIL, CPF, TELEFONE) VALUES('Fabiana Ferraz', 'ferraz@fiap.com.br',
                        '32422', '(11) 98423423');

INSERT INTO PESSOA(NOME, EMAIL, CPF, TELEFONE) VALUES('Fernando Lopes', 'lopes@fiap.com.br',
                        '23432432', '(11) 72343223');

insert into funcionario (pessoa_id, cargo, departamento, admissao, salario) values(12, 'Analista', 'IT',
        to_date('2017-01-20', 'YYYY-MM-DD'), 7800.45);

insert into funcionario (pessoa_id, cargo, departamento, admissao, salario) values(13, 'Professor', 'Ensino',
        to_date('2019-02-10', 'YYYY-MM-DD'), 2000.45);

insert into funcionario (pessoa_id, cargo, departamento, admissao, salario) values(14, 'Arquiteto', 'IT',
        to_date('2022-07-20', 'YYYY-MM-DD'), 14478);


