package br.com.fiap.enquete.model;

import java.time.LocalDateTime;

public class Resposta {

    /**
     create table resposta(id number generated by default as identity,
                           valor varchar(200),
                           data timestamp,
                           pessoa varchar(100),
                           pergunta_id number,
                           primary key(id),
                           foreign key(pergunta_id) references pergunta(id));
     */


    private long id;
    private String valor;
    private Pergunta pergunta;
    private LocalDateTime data;
    private String pessoa;

    public LocalDateTime getData() {
        return data;
    }

    public void setData(LocalDateTime data) {
        this.data = data;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Pergunta getPergunta() {
        return pergunta;
    }

    public void setPergunta(Pergunta pergunta) {
        this.pergunta = pergunta;
    }

    public String getPessoa() {
        return pessoa;
    }

    public void setPessoa(String pessoa) {
        this.pessoa = pessoa;
    }

    public String getValor() {
        return valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
    }

    //pode colocar novos atributos aqui


}
